### ISSUE TITLE
TypeError: lineDataAccessor.forEach is not a function

### ISSUE THREAD

**Issue by strictlymomo** [emeeks/semiotic#297]
I had functioning line charts using ResponsiveXYFrame in 1.11.13.  Since updating to version 1.11.14 and above, I receive the following error.

<img width="819" alt="screen shot 2018-07-26 at 4 36 23 pm" src="https://user-images.githubusercontent.com/8671427/43248664-881094be-90f3-11e8-9741-0b53ee938a53.png">

**Comment by emeeks** [comment]
Could you post your settings?

**Comment by strictlymomo** [comment]
Thanks very much for your attention.  Again, this happened when upgrading from 1.11.13 to 1.11.14. 
If it's not a mistake on my end, might it be related to a recent issue concerning [debouncing](https://github.com/emeeks/semiotic/issues/286) or change sometime around this [commit](https://github.com/emeeks/semiotic/commit/25006ac1232746e8db9d56a9b306df70da4716c3)?

**TellersTimeline.js**
``` 
import React, { Component } from 'react'
import { ResponsiveXYFrame } from 'semiotic'
import Typography from '@material-ui/core/Typography'
import { curveCardinal } from 'd3-shape'
import { scaleTime } from 'd3-scale'
import colors from '../../utilities/colors'

export default class TellersTimeline extends Component {

  render() {
    return (
      <ResponsiveXYFrame
        size={[500,150]}
        responsiveWidth={true}
        lines={this.props.graphData}
        xScaleType={scaleTime()}
        xAccessor={d => new Date(d.day)}
        yAccessor={d => d.totalTellersRegistered}
        lineStyle={{stroke: colors.palette.blue, strokeWidth: 3}}
        lineType={{type: "line",  interpolator: curveCardinal.tension(.75)}}
        hoverAnnotation={true}
        tooltipContent={d =>
          <div className="tooltip-content">
            <Typography variant="caption">{d.day}</Typography>
            <Typography variant="title">{d.totalTellersRegistered} active tellers</Typography>
          </div>}
        margin={{left: 30, bottom: 40, right: 10, top: 13}}
        axes={[
          {
            orient: "left"
          },
          {
            orient: "bottom",
            tickFormat: d => d.getMonth() + "/" + d.getDate()
          }
        ]}
      />
    )
  }
}
```

**App.js + CSS**
```
...
<div className={'chart-container'}>
    <TellersTimeline graphData={this.state.tellersTimeline}/>
</div>
...

.chart-container {
    display: flex;
}
```

**graphData**
<img width="604" alt="screen shot 2018-07-27 at 1 04 09 am" src="https://user-images.githubusercontent.com/8671427/43274192-6f248c4e-9139-11e8-8baa-0148d6898cb3.png">

**Comment by emeeks** [comment]
Closing this assuming the fix worked. Feel free to reopen or open a new issue if you still see any problems.
